version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    container_name: camps_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: CampsManager
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - /opt/mariadb:/var/lib/mysql
      - ./:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
